classdef headerEngine < handle
    % build the full header

    properties
        MACHeader
        PHYHeader
        fullHeaderBits
        fullHeaderSpreadBits
        fullHeaderSyms
        frameSymsBlocked
    end

    properties (Access= private)
        pScramblerSeedID = [ 0; 0; 0; 0]
        pHCS 
        pScrambledMACHCS 
        pStuffBits
    end 

    methods
        function obj = headerEngine(phyHeader,macHeader)
            obj.PHYHeader = phyHeader(:); % column vecs
            obj.MACHeader = macHeader(:);


            obj.build()
        end
        
        function obj = build(obj)
            obj.headerCheckSequence();
            obj.scrambleMACCRC();
            obj.extendedHamming();
            obj.stuffBits();
            obj.spreadCode();
            obj.modulate();
            obj.blockBuilder();
        end % build

        function obj = headerCheckSequence(obj)
            phyMac = [obj.PHYHeader; obj.MACHeader];

            hcsGen = comm.CRCGenerator(...
                'Polynomial', 'x^16 + x^15 + x^13 + x^8 + x^5 + x^3+ x + 1', ...
                'InitialConditions', 1, ...      % Initialize to all ones
                'DirectMethod', false, ...       % Indirect method (remainder generated by mod2)
                'ReflectInputBytes', false, ...  % Turn off to allow 117 bits
                'ReflectChecksums', false, ...   % Turn off to allow 117 bits
                'FinalXOR', 1);                 % Inverts the remainder (ones' complement)
            
            crcOut = hcsGen(phyMac);
            obj.pHCS = crcOut(end-15:end);
        end % header check sequence

        function obj = scrambleMACCRC(obj)
            %% the scramble and descramble are idenetical, reuse the function for both 
            dataBits = [obj.MACHeader; obj.pHCS]; 
            scramblerSeedID = obj.pScramblerSeedID;
            
            % [1 1 0 1 0 0 0 0 1 0 1 S1 S2 S3 S4]
            xInit = [1; 1; 0; 1; 0; 0; 0; 0; 1; 0; 1; scramblerSeedID]; %12-13
            
            scrambledBits = zeros(length(dataBits), 1);
            for n = 1:length(dataBits)
                xn = xor(xInit(14), xInit(15)); % 12-12
                scrambledBits(n) = xor(dataBits(n), xn); % 12-14
                xInit = [xn; xInit(1:14)]; % shift
            end
            obj.pScrambledMACHCS = scrambledBits;
        end % scrambler

        function obj = extendedHamming(obj)
            Pmat = [1 1 0 1;...
                0 1 1 1;...
                1 0 1 1;...
                1 1 1 0];

                Gmat = [eye(4) Pmat]; % [I P]
                % Hmat = [Pmat' I4]; % [P^T I]
       
            dataBits = [obj.PHYHeader; obj.pScrambledMACHCS]; % column vector
            
            % (8,4) coding need groups of 4
            padLen = mod(4 - mod(length(dataBits), 4), 4);
            paddedData = [dataBits; zeros(padLen, 1)];
            
            bitMatrix = reshape(paddedData,4,[]); %nx4
            encodedBitsM = mod(bitMatrix'*Gmat,2); % * will do linear matrix multi
            encodedBitsVec = reshape(encodedBitsM',[],1);% not the transpose for this to work
            
            obj.fullHeaderBits = encodedBitsVec;
        end % exteneded hamming  

        function obj = stuffBits(obj)
            size = 40; % hardcoded see table (14-7)
            obj.pStuffBits = zeros(size,1);
            obj.fullHeaderBits = [obj.fullHeaderBits; obj.pStuffBits];
        end % stuff bits

        function obj = spreadCode(obj)
            code0 = 1010;
            code1 = 0101;
            SF = 4; % spreading factor

            word = obj.fullHeaderBits;
            wordLength = length(word);
            codeWordLength = wordLength * SF;
            codeWord = zeros(1,codeWordLength);
        
            
            for i = 1:codeWordLength
                startIDX = (i-1)*SF + 1;
                endIDX = startIDX + SF - 1;
                if word(i) == 0 
                    codeWord(startIDX:endIDX) = code0;
                else
                    codeWord(startIDX:endIDX) = code1;
                end  
            end
            obj.fullHeaderSpreadBits;
        end % spreader 

        function obj = modulate(obj)
            bits = obj.fullHeaderSpreadBits;
            n = (0:length(bits)-1).';
            bipolarBits = 2*bits -1;
            rotatedBits = bipolarBits .*(1j*pi/2*n);
            obj.fullHeaderSyms = rotatedBits;
        end % modulate

        function obj = blockBuilder(obj)
            % table (14-7)
            numBLock = 19;
            blockSize = 64;
            PWsize = 8;
            wordSize = blockSize- PWsize;

            frameModulated = obj.fullHeaderSyms;
            if length(frameModulated) ~= (numBLock * wordSize)
                warning('Header Size incorrect')
                numError = (numBLock * wordSize) - length(frameModulated);
                padding = zeros(numError,1);
                frameModulated = [frameModulated; padding];
                warning('Header padded %d zeros',numError);
            end

            pilotWord = [1 1 0 1 0 1 1 1]; %0xEB
            n = 0:7;
            PW = (2*pilotWord-1).*exp(1j*pi/2*n);
            symsMat = reshape(frameModulated,blockSize,[]).';
            [numRow,numCol] = size(symsMat);
            PWMat = repmat(PW,numRow,1);
            symsMat_PWMat = [symsMat PWMat];
            frameSymsBlocked = reshape(symsMat_PWMat.',[],1);

            obj.frameSymsBlocked = frameSymsBlocked; 
        end % block builder
    end
end
