classdef headerEngine
    % build the full header

    properties
        MACHeader
        PHYHeader
        fullHeader
    end

    properties (Access= private)
        pScramblerSeedID = [ 0; 0; 0; 0]
        pHCS 
        pScrambledMACHCS 
    end 

    methods
        function obj = headerEngine(phyHeader,macHeader)
            obj.PHYHeader = phyHeader(:); % column vecs
            obj.MACHeader = macHeader(:);


            obj.build()
        end
        
        function obj = build(obj)
            obj.headerCheckSequence();
            obj.scrambleMACCRC();
            obj.extendedHamming();
        end % build

        function obj = headerCheckSequence(obj)
            phyMac = [obj.PHYHeader; obj.MACHeader];

            hcsGen = comm.CRCGenerator(...
                'Polynomial', 'x^16 + x^15 + x^13 + x^8 + x^5 + x^3+ x + 1', ...
                'InitialConditions', 1, ...      % Initialize to all ones
                'DirectMethod', false, ...       % Indirect method (remainder generated by mod2)
                'ReflectInputBytes', false, ...  % Turn off to allow 117 bits
                'ReflectChecksums', false, ...   % Turn off to allow 117 bits
                'FinalXOR', 1);                 % Inverts the remainder (ones' complement)
            
            crcOut = hcsGen(phyMac);
            obj.pHCS = crcOut(end-16:end);
        end % header check sequence

        function obj = scrambleMACCRC(obj)
            %% the scramble and descramble are idenetical, reuse the function for both 
            dataBits = [obj.MACHeader; obj.pHCS]; 
            scramblerSeedID = obj.pScramblerSeedID;
            
            % [1 1 0 1 0 0 0 0 1 0 1 S1 S2 S3 S4]
            xInit = [1; 1; 0; 1; 0; 0; 0; 0; 1; 0; 1; scramblerSeedID]; %12-13
            
            scrambledBits = zeros(length(dataBits), 1);
            for n = 1:length(dataBits)
                xn = xor(xInit(14), xInit(15)); % 12-12
                scrambledBits(n) = xor(dataBits(n), xn); % 12-14
                xInit = [xn; xInit(1:14)]; % shift
            end
            obj.pScrambledMACHCS = scrambledBits;
        end % scrambler

        function obj = extendedHamming(obj)
            Pmat = [1 1 0 1;...
                0 1 1 1;...
                1 0 1 1;...
                1 1 1 0];

                Gmat = [eye(4) Pmat]; % [I P]
                % Hmat = [Pmat' I4]; % [P^T I]
       
            dataBits = [obj.PHYHeader; obj.pScrambledMACHCS]; % column vector
            
            % (8,4) coding need groups of 4
            padLen = mod(4 - mod(length(dataBits), 4), 4);
            paddedData = [dataBits; zeros(padLen, 1)];
            
            numBlocks = length(paddedData) / 4;
            encodedBits = zeros(numBlocks * 8, 1);
            
            for n = 0:numBlocks-1
                blockData = paddedData(n*4 + (1:4));
                encodedBlock = mod(blockData' * G, 2);
                encodedBits(n*8 + (1:8)) = encodedBlock';
            end
            
            obj.fullHeader = encodedBits;
        end % exteneded hamming  
    end
end
