      %% Steve arbogast
% 525.752
% Header Check Sequence HCS
% CRC 16
% 13.2.4.3.3 Header check sequence (HCS)
% The combination of the PHY header and MAC header shall be protected with a CRC-16 HCS. The MAC
% parameter pLengthHCS shall be 2 for this PHY. The CRC-16 HCS shall be the ones complement of the
% remainder generated by the modulo-2 division of the protected combined PHY and MAC headers by the
% polynomial:
% x16 + x15 + x13 + x8 + x5 + x3+ x + 1

clear
%% 
macHeaderObj = macHeaderClass();
macHeader = macHeaderObj.getProp('MACheader');
phyHeaderObj = phyHeaderClass();
phyHeader = phyHeaderObj.getProp('PHYheader');

phyMac = [phyHeader macHeader];
phyMac = phyMac(:);
checksumLength = 16;

% crcCfg = crcConfig( ...
%     Polynomial = 'x^16 + x^15 + x^13 + x^8 + x^5 + x^3+ x + 1',...
%     InitialConditions=1, ... % intialize to all ones
%     DirectMethod= false, ... % use indirect; remainder generated by mod2
%     ReflectChecksums = true,... % LSB first
%     FinalXOR=1); % ones complement 
hcsGen = comm.CRCGenerator(...
    'Polynomial', 'x^16 + x^15 + x^13 + x^8 + x^5 + x^3+ x + 1', ...
    'InitialConditions', 1, ...      % Initialize to all ones
    'DirectMethod', false, ...       % Indirect method (remainder generated by mod2)
    'ReflectInputBytes', false, ...  % Turn off to allow 117 bits
    'ReflectChecksums', false, ...   % Turn off to allow 117 bits
    'FinalXOR', 1);                 % Inverts the remainder (ones' complement)

txStream = hcsGen(phyMac); 
% crcSeq = crcGenerate(phyMac,crcCfg);
% checkSum =  crcSeq(end-checksumLength+1:end);

hcsDetect = comm.CRCDetector(...
    'Polynomial', 'x^16 + x^15 + x^13 + x^8 + x^5 + x^3+ x + 1', ...
    'InitialConditions', 1, ...      % Initialize to all ones
    'DirectMethod', false, ...       % Indirect method (remainder generated by mod2)
    'ReflectInputBytes', false, ...  % Turn off to allow 117 bits
    'ReflectChecksums', false, ...   % Turn off to allow 117 bits
    'FinalXOR', 1);                 % Inverts the remainder (ones' complement)

% validate adn get macphy back
[cleanData, errorFlag] = hcsDetect(txStream); %errorFlag = 0 is valid



