%% Steve arbogast
% 525.752
% Header Check Sequence HCS
% CRC 16
% 13.2.4.3.3 Header check sequence (HCS)
% The combination of the PHY header and MAC header shall be protected with a CRC-16 HCS. The MAC
% parameter pLengthHCS shall be 2 for this PHY. The CRC-16 HCS shall be the ones complement of the
% remainder generated by the modulo-2 division of the protected combined PHY and MAC headers by the
% polynomial:
% x16 + x15 + x13 + x8 + x5 + x3+ x + 1

clear
%% 
macHeaderObj = macHeaderClass();
macHeader = macHeaderObj.getProp('MACheader');
phyHeaderObj = phyHeaderClass();
phyHeader = phyHeaderObj.getProp('PHYheader');



Address = [1 0 0 0 0 0 0 0];
UA = [1 1 0 0 1 1 1 0];
input = [Address UA]';
expectedChecksum = [1 1 0 0 0 0 0 1 1 1 1 0 1 0 1 0]'; % Expected FCS
checksumLength = 16;

crcCfg = crcConfig( ...
    Polynomial='X^16 + X^12 + X^5 + 1', ...
    InitialConditions=1, ...
    DirectMethod=true, ...
    FinalXOR=1);
crcSeq = crcGenerate(input,crcCfg);
checkSum =  crcSeq(end-checksumLength+1:end);
